### ISSUE TITLE
SOLVED: error: matrix_hal/everloop_image.h: No such file or directory

### ISSUE THREAD

**Issue by technodromeltd** [matrix-io/matrix-creator-alexa-voice-demo#2]
following instructions, last command 

```
pi@matrix:~/matrix-creator-alexa-voice-demo/micarray/build $ make
Scanning dependencies of target micarray_dump
[100%] Building CXX object CMakeFiles/micarray_dump.dir/micarray_dump.cpp.o
/home/pi/matrix-creator-alexa-voice-demo/micarray/micarray_dump.cpp:13:39: fatal error: matrix_hal/everloop_image.h: No such file or directory
 #include <matrix_hal/everloop_image.h>
                                       ^
compilation terminated.
CMakeFiles/micarray_dump.dir/build.make:54: recipe for target 'CMakeFiles/micarray_dump.dir/micarray_dump.cpp.o' failed
make[2]: *** [CMakeFiles/micarray_dump.dir/micarray_dump.cpp.o] Error 1
CMakeFiles/Makefile2:60: recipe for target 'CMakeFiles/micarray_dump.dir/all' failed
make[1]: *** [CMakeFiles/micarray_dump.dir/all] Error 2
Makefile:76: recipe for target 'all' failed
make: *** [all] Error 2

```

advide @eljuguetero ?

**Comment by technodromeltd** [comment]
Jumping from guides to guide doesnt really keep you sane... So  I guess i just needed to build the hal files that I though I did, so this part I was missing:

```
cd matrix-creator-hal
mkdir build
cd build
cmake ../
make
sudo make install

```

**Comment by R34SGA** [comment]
ended up on the same issue following this guide [https://www.hackster.io/matrix-labs/direction-of-arrival-for-matrix-voice-creator-using-odas-b7a15b](https://www.hackster.io/matrix-labs/direction-of-arrival-for-matrix-voice-creator-using-odas-b7a15b) 

It just meant i forgot this part (thinking it was already done but it wasn't)
_Install MATRIX Dependancies (one at a time)

sudo apt install matrixio-creator-init
sudo apt install libmatrixio-creator-hal
sudo apt install libmatrixio-creator-hal-dev_

Hoping it will help someone else ;)
